version: "3"
services:

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/MyCert.crt:/etc/nginx/MyCert.crt"
      - "./conf/MyKey.key:/etc/nginx/MyKey.key"
    depends_on:
      - keycloak_n1
      - keycloak_n2
    networks:
      - public_network
      - private_network

  infinispan:
    image: quay.io/infinispan/server:11.0.9.Final
    ports:
      - "11222:11222"
    environment:
      - USER=${ISPN_USERNAME}
      - PASS=${ISPN_PASSWORD}
    networks:
      - private_network

  keycloak_n1:
    image: "quay.io/keycloak/keycloak:17.0.0"
    ports:
      - "1443:1443"
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
####### Config Infinispan Cache ##########
      - KC_CACHE=ispn
      - KC_CACHE_CONFIG_FILE=/cache-config/cache-ispn.xml
####### Config Postgresql Database #######
      - KC_DB=postgres
      - KC_DB_URL_HOST=pg_sql:5432
      - KC_DB_URL_DATABASE=${DB_NAME}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_SCHEMA=public
####### Config HTTPS ##########
      - KC_HTTPS_PORT=1443
      - KC_HTTP_ENABLED=false
      - KC_HTTPS_KEY_STORE_FILE=/https-config/server.keystore
####### Config the proxy for the load balancer
      - KC_HOSTNAME=keycloak.cluster.com
      - KC_HOSTNAME_PORT=443
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_PROXY=reencrypt
    command:
      start --auto-build
    volumes:
      - "./conf/server.keystore:/https-config/server.keystore"
      - "./conf/cache-ispn.xml:/cache-config/cache-ispn.xml"
    depends_on:
      - pg_sql
      - infinispan
    networks:
      - private_network

  keycloak_n2:
    image: "quay.io/keycloak/keycloak:17.0.0"
    ports:
      - "2443:2443"
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
####### Config Infinispan Cache ##########
      - KC_CACHE=ispn
      - KC_CACHE_CONFIG_FILE=/cache-config/cache-ispn.xml
####### Config Postgresql Database #######
      - KC_DB=postgres
      - KC_DB_URL_HOST=pg_sql:5432
      - KC_DB_URL_DATABASE=${DB_NAME}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_SCHEMA=public
####### Config HTTPS ##########
      - KC_HTTPS_PORT=2443
      - KC_HTTP_ENABLED=false
      - KC_HTTPS_KEY_STORE_FILE=/https-config/server.keystore
####### Config the proxy for the load balancer
      - KC_HOSTNAME=keycloak.cluster.com
      - KC_HOSTNAME_PORT=443
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_PROXY=reencrypt
    command:
      start --auto-build
    volumes:
      - "./conf/server.keystore:/https-config/server.keystore"
      - "./conf/cache-ispn.xml:/cache-config/cache-ispn.xml"
    depends_on:
      - pg_sql
      - infinispan
    networks:
      - private_network

  pg_sql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - private_network

volumes:
  postgres_data:
      driver: local


networks:
  public_network:
    internal: false
  private_network:
    internal: true
